import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { expect, it } from "vitest";
import { McpArtifactStore } from "../src/main/mcp/mcpArtifactStore";
import { McpOutputDeliveryObserver } from "../src/main/mcp/mcpOutputDeliveryObserver";
import type { McpExchangeBinding } from "../src/shared/mcpExchangeFiles";
import {
  deliveryArtifactFixture,
  deliveryBinding,
  deliveryResponseFinished,
  deliveryTemporaryFile,
} from "./mcpOutputDeliveryArtifact.fixture";

it("tracks generated and reissued capabilities together only after successful admission", async () => {
  const retainedOutputId = randomUUID();
  const bytes = Buffer.from("synthetic exact retained bytes");
  const retained = await deliveryTemporaryFile(bytes);
  const f = await deliveryArtifactFixture(async (_artifact, guard) => {
    await guard();
    return retainedOutputId;
  });
  try {
    const generated = await f.store.put(bytes, f.assertAccess, deliveryBinding);
    const reissued = await f.store.issueRetained(
      retained.file,
      {
        mimeType: "image/png",
        bytes: bytes.length,
        sha256: generated.sha256,
        bindings: [deliveryBinding],
        retainedOutputId,
      },
      f.assertAccess,
      f.assertAccess,
    );
    const reference = await f.store.observation(generated.url);
    expect(reference.retainedOutputId).toBe(retainedOutputId);
    expect(reference.artifactKey).toMatch(/^[a-f0-9]{64}$/);
    expect(reference).not.toHaveProperty("url");
    await f.store.disclosed(generated.url, false);
    await f.store.disclosed(reissued.url, true);
    const secret = new URL(generated.url).pathname.split("/")[2];
    expect((await f.store.read(secret)).equals(bytes)).toBe(true);
    expect(f.observer.inspect(reference)).toMatchObject({
      capabilities: { generated: 1, reissued: 1 },
      toolResponsesPrepared: { text: 2, attachment: 1 },
      http: { getStarted: 0, headStarted: 0 },
    });
    expect(
      Buffer.from(await (await f.send(generated.url)).arrayBuffer()).equals(
        bytes,
      ),
    ).toBe(true);
    expect(
      (await (await f.send(reissued.url, { method: "HEAD" })).arrayBuffer())
        .byteLength,
    ).toBe(0);
    expect(f.observer.inspect(reference)).toMatchObject({
      http: { getCompleted: 1, headCompleted: 1, bytesQueued: bytes.length },
    });
    expect(JSON.stringify(f.observer.inspect(reference))).not.toContain(secret);
    await f.store.close();
    expect((await readFile(retained.file)).equals(bytes)).toBe(true);
  } finally {
    await f.close();
    await retained.close();
  }
});

it("does not record generation when access is revoked during retained publication", async () => {
  const retainedOutputId = randomUUID();
  const observer = new McpOutputDeliveryObserver();
  const failure = new Error("Revoked while retention persisted");
  let allowed = true;
  const store = new McpArtifactStore(
    "https://delivery.test",
    Date.now,
    async (_artifact, guard) => {
      await guard();
      allowed = false;
      return retainedOutputId;
    },
    observer,
  );
  try {
    await expect(
      store.put(
        Buffer.from("generated bytes"),
        async () => {
          if (!allowed) throw failure;
        },
        deliveryBinding,
      ),
    ).rejects.toBe(failure);
    expect(observer.inspect({ retainedOutputId })).toMatchObject({
      state: "not_observed",
    });
  } finally {
    await store.close();
  }
});

it("rejects foreign capabilities, wrong suffixes and revoked access before disclosure or HTTP observation", async () => {
  const f = await deliveryArtifactFixture();
  try {
    const output = await f.store.put(
      Buffer.from("synthetic transport bytes"),
      f.assertAccess,
    );
    const reference = await f.store.observation(output.url);
    await expect(
      f.store.observation(output.url.replace("delivery.test", "foreign.test")),
    ).rejects.toMatchObject({ code: "not_found" });
    await expect(
      f.store.disclosed(output.url.replace("page.png", "context.json"), true),
    ).rejects.toMatchObject({ code: "not_found" });
    expect(
      (await f.send(output.url.replace("page.png", "context.json"))).status,
    ).toBe(404);
    expect((await f.send(output.url, { method: "POST" })).status).toBe(405);
    f.revoke();
    await expect(f.store.disclosed(output.url, true)).rejects.toBe(f.revoked);
    for (const method of ["GET", "HEAD"])
      expect((await f.send(output.url, { method })).status).toBe(404);
    expect(f.observer.inspect(reference)).toMatchObject({
      toolResponsesPrepared: { text: 0, attachment: 0 },
      http: { getStarted: 0, headStarted: 0 },
    });
    expect(f.errors).toEqual([]);
  } finally {
    await f.close();
  }
});

const textBinding = (format: "txt" | "csv" | "tsv"): McpExchangeBinding => ({
  kind: "text",
  workId: "work",
  chapterId: "chapter",
  pages: [{ pageId: "page", revision: deliveryBinding.revision }],
  options:
    format === "txt"
      ? { format, field: "both", includeHeaders: true }
      : { format, includeBom: false },
  direction: "ltr",
  snapshot: "0".repeat(16),
});
const exchangeCases: {
  name: string;
  mimeType: string;
  binding: McpExchangeBinding;
}[] = [
  { name: "text.txt", mimeType: "text/plain", binding: textBinding("txt") },
  { name: "review.csv", mimeType: "text/csv", binding: textBinding("csv") },
  {
    name: "review.tsv",
    mimeType: "text/tab-separated-values",
    binding: textBinding("tsv"),
  },
  {
    name: "context.json",
    mimeType: "application/json",
    binding: {
      kind: "context",
      workId: "work",
      chapterId: "chapter",
      scope: "guide",
      snapshot: "0".repeat(16),
    },
  },
];
it.each(exchangeCases)(
  "serves fixed $name bytes and observes HEAD separately through real HTTP",
  async ({ name, mimeType, binding }) => {
    const f = await deliveryArtifactFixture();
    const bytes = Buffer.from("synthetic UTF-8 exchange: 번역\n");
    try {
      const output = await f.store.putExchange(
        bytes,
        binding,
        f.assertAccess,
        new AbortController().signal,
      );
      const reference = await f.store.observation(output.url);
      const head = await f.send(output.url, { method: "HEAD" });
      expect(head.status).toBe(200);
      expect((await head.arrayBuffer()).byteLength).toBe(0);
      const response = await f.send(output.url);
      expect(response.status).toBe(200);
      expect(response.headers.get("content-type")).toBe(mimeType);
      expect(response.headers.get("content-disposition")).toBe(
        `attachment; filename="carrot-${name}"`,
      );
      expect(response.headers.get("content-length")).toBe(String(bytes.length));
      expect(response.headers.get("cache-control")).toBe("no-store");
      expect(response.headers.get("referrer-policy")).toBe("no-referrer");
      expect(response.headers.get("x-content-type-options")).toBe("nosniff");
      expect(Buffer.from(await response.arrayBuffer()).equals(bytes)).toBe(
        true,
      );
      expect(f.observer.inspect(reference)).toMatchObject({
        capabilities: { generated: 1, reissued: 0 },
        http: {
          getCompleted: 1,
          headCompleted: 1,
          inFlight: 0,
          bytesQueued: bytes.length,
        },
      });
      expect(f.errors).toEqual([]);
    } finally {
      await f.close();
    }
  },
);

it("records exact streamed working-file bytes after response completion", async () => {
  const f = await deliveryArtifactFixture();
  const bytes = Buffer.alloc(1024 * 1024 + 17, 0x61);
  let completion: ReturnType<typeof deliveryResponseFinished> | undefined;
  try {
    const output = await f.workFile(bytes);
    const reference = await f.store.observation(output.url);
    completion = deliveryResponseFinished(output.url);
    expect(
      Buffer.from(await (await f.send(output.url)).arrayBuffer()).equals(bytes),
    ).toBe(true);
    expect((await completion.finished).writableFinished).toBe(true);
    expect(f.observer.inspect(reference)).toMatchObject({
      http: { getCompleted: 1, bytesQueued: bytes.length, inFlight: 0 },
    });
  } finally {
    completion?.close();
    await f.close();
  }
});
