import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

describe("prompt contracts", () => {
  it("keeps one canonical overlay prompt with tight Japanese glyph bbox rules", () => {
    const runtimeSource = readFileSync(join(process.cwd(), "src/main/runtime/simple-page-translate.cjs"), "utf8");
    const promptSource = readFileSync(join(process.cwd(), "src/main/runtime/simple-page-prompts.cjs"), "utf8");
    const pipelineSource = readFileSync(join(process.cwd(), "src/main/wholePagePipeline.ts"), "utf8");
    const contractSource = `${promptSource}\n${runtimeSource}`;

    expect(promptSource).toContain("const OVERLAY_PROMPT_SECTIONS");
    expect(contractSource).toContain("x1, y1, x2, y2 describe the tight rectangle corners of the visible Japanese glyph ink and its outline.");
    expect(contractSource).toContain("Return x1, y1, x2, y2 as integer pixel coordinates");
    expect(contractSource).toContain("fontSize is the apparent Japanese glyph size in Image 1 pixels.");
    expect(contractSource).toContain("Each speech bubble is one dialogue item.");
    expect(contractSource).toContain("If two white balloon lobes touch, overlap, stack vertically, or connect through a narrow neck");
    expect(contractSource).toContain("For SFX, box only the sound-effect glyph strokes");
    expect(contractSource).toContain("type must always be nonsolid.");
    expect(contractSource).toContain("The app uses one Flux-based inpainting path for every text block");
    expect(contractSource).toContain("For sound-effect or reaction lettering, ko must be bare Korean effect lettering only");
    expect(contractSource).toContain("do not wrap it in parentheses/brackets/quotes");
    expect(contractSource).toContain("preserve the original visible sound texture first");
    expect(contractSource).toContain("Do not force every SFX into semantic Korean");
    expect(contractSource).toContain("For repeated or lengthened SFX, preserve the visible rhythm and duration");
    expect(contractSource).toContain("Do not translate ambient SFX as spoken dialogue");
    expect(contractSource).toContain("Do not output isolated fragments as separate records");
    expect(contractSource).toContain("Skip records whose jp is only punctuation");
    expect(contractSource).not.toContain("ざわざわ/ザワザワ");
    expect(contractSource).not.toContain("ギュル/ギュルル");
    expect(contractSource).not.toContain("ダァ/ダー");
    expect(contractSource).not.toContain("재능");
    expect(contractSource).toContain("Coordinate calibration");
    expect(contractSource).toContain("Use the full visible Image 1 frame as the coordinate frame");
    expect(contractSource).toContain("detail: \"original\"");
    expect(contractSource).toContain("bboxCoordinateSpace");
    expect(contractSource).toContain("Use exactly these keys, one per line: id, type, x1, y1, x2, y2, direction, angle, fontSize, confidence, jp, ko.");
    expect(contractSource).toContain("confidence is your confidence from 0.00 to 1.00");
    expect(contractSource).toContain("You are directly OCR-reading and translating only the listed manga crop images.");
    expect(contractSource).toContain("The crop image itself is the authority.");
    expect(contractSource).toContain("textRole is one of sound, ordinary, or nontext.");
    expect(contractSource).toContain("x1, y1, x2, y2 are integer crop image pixel coordinates");
    expect(contractSource).toContain("For sound-check targets");
    expect(contractSource).toContain("OCR bbox candidates");
    expect(contractSource).toContain("low-trust OCR text hints for slot matching only");
    expect(contractSource).toContain("Use Image 1 as the authority");
    expect(contractSource).toContain("Treat each candidate as a locked geometry slot.");
    expect(contractSource).toContain("Do not merge two candidates into one record");
    expect(contractSource).toContain("For every accepted candidate, output type nonsolid.");
    expect(contractSource).not.toContain("buildPointDetectionPrompt");
    expect(contractSource).not.toContain("buildPointExpansionPrompt");
    expect(pipelineSource).not.toContain("function buildRetryPrompt");
    expect(pipelineSource).not.toContain("promptOverrideText: attempt > 1");
  });
});
