[package]
name = "mgt-import-source-runner"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
publish = false

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
hayro = "0.7.1"
memmap2 = "0.9.9"
rars = "0.6.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[dev-dependencies]
tempfile = "3.24.0"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
panic = "abort"
