export const FLUX_INPAINT_CONTEXT_PX = 160;
export const FLUX_METAL_INPAINT_CONTEXT_PX = 96;
export const FLUX_INPAINT_MASK_PADDING_PX = 16;
export const FLUX_RUNNER_MASK_PADDING_PX = 0;
export const FLUX_INPAINT_FEATHER_PX = 8;
export const FLUX_INPAINT_MAX_PIXELS = 1024 * 1024;
export const FLUX_INPAINT_MULTIPLE = 16;
export const FLUX_METAL_TILE_SIZE_PX = 512;
