import { isDeepStrictEqual } from "node:util";
import type { BubbleLayout } from "../../shared/bubbleLayout";
import type { MangaPage } from "../../shared/libraryTypes";
import type { BBox, TranslationBlock } from "../../shared/textTypes";

type RenderBboxSpace = NonNullable<TranslationBlock["renderBboxSpace"]>;

/**
 * Exact state used by the inpainting history transaction.
 *
 * Geometry-only captures omit `translatedText`, preserving the original
 * render-only history contract. Callers may explicitly include it when the
 * same transaction must undo or redo a generated translation.
 *
 * `null` means that the optional geometry property is absent. Keeping that
 * distinction lets undo remove a layout generated by the postprocessor
 * without touching the source detection bbox or any user formatting.
 */
export type InpaintingBlockLayoutState = {
  blockId: string;
  renderBbox: BBox | null;
  renderBboxSpace: RenderBboxSpace | null;
  bubbleLayout: BubbleLayout | null;
  translatedText?: string;
};

export type InpaintingPageLayoutPatch = {
  pageId: string;
  states: InpaintingBlockLayoutState[];
  /** Optional optimistic-concurrency guard checked at the chapter commit point. */
  expectedStates?: InpaintingBlockLayoutState[];
};

export function captureInpaintingLayoutStates(
  page: Pick<MangaPage, "blocks">,
  blockIds: readonly string[],
  options: { includeTranslatedText?: boolean } = {},
): InpaintingBlockLayoutState[] {
  return captureSelectedInpaintingLayoutStates(
    page,
    blockIds,
    () => options.includeTranslatedText === true,
  );
}

function captureSelectedInpaintingLayoutStates(
  page: Pick<MangaPage, "blocks">,
  blockIds: readonly string[],
  includeTranslatedText: (index: number) => boolean,
): InpaintingBlockLayoutState[] {
  const blocksById = new Map(page.blocks.map((block) => [block.id, block]));
  const seen = new Set<string>();
  return blockIds.map((blockId, index) => {
    if (seen.has(blockId)) {
      throw new Error("말풍선 배치 기록에 같은 블록이 중복되었습니다.");
    }
    seen.add(blockId);
    const block = blocksById.get(blockId);
    if (!block) {
      throw new Error("말풍선 배치를 적용할 텍스트 블록을 찾지 못했습니다.");
    }
    const bubbleLayout = block.bubbleLayout;
    const state: InpaintingBlockLayoutState = {
      blockId,
      renderBbox: block.renderBbox ? cloneSerializable(block.renderBbox) : null,
      renderBboxSpace: block.renderBboxSpace ?? null,
      bubbleLayout:
        bubbleLayout === undefined ? null : cloneSerializable(bubbleLayout),
    };
    if (includeTranslatedText(index)) {
      assertStoredTranslatedText(block.translatedText);
      state.translatedText = block.translatedText;
    }
    return state;
  });
}

export function applyInpaintingLayoutStates<
  TPage extends Pick<MangaPage, "blocks">,
>(page: TPage, states: readonly InpaintingBlockLayoutState[]): TPage {
  if (states.length === 0) {
    return page;
  }
  const stateById = new Map<string, InpaintingBlockLayoutState>();
  for (const state of states) {
    if (stateById.has(state.blockId)) {
      throw new Error("말풍선 배치 기록에 같은 블록이 중복되었습니다.");
    }
    assertStoredRenderBbox(state.renderBbox);
    if (hasOwnTranslatedText(state)) {
      assertStoredTranslatedText(state.translatedText);
    }
    stateById.set(state.blockId, state);
  }
  const knownIds = new Set(page.blocks.map((block) => block.id));
  for (const blockId of stateById.keys()) {
    if (!knownIds.has(blockId)) {
      throw new Error("말풍선 배치를 적용할 텍스트 블록을 찾지 못했습니다.");
    }
  }

  return {
    ...page,
    blocks: page.blocks.map((block) => {
      const state = stateById.get(block.id);
      if (!state) {
        return block;
      }
      const next: TranslationBlock = { ...block };
      if (state.renderBbox === null) {
        delete next.renderBbox;
        delete next.renderBboxSpace;
      } else {
        next.renderBbox = cloneSerializable(state.renderBbox);
        if (state.renderBboxSpace === null) {
          delete next.renderBboxSpace;
        } else {
          next.renderBboxSpace = state.renderBboxSpace;
        }
      }
      if (state.bubbleLayout === null) {
        delete next.bubbleLayout;
      } else {
        next.bubbleLayout = cloneSerializable(state.bubbleLayout);
      }
      if (hasOwnTranslatedText(state)) {
        const translatedText = state.translatedText;
        assertStoredTranslatedText(translatedText);
        next.translatedText = translatedText;
      }
      return next;
    }),
  };
}

export function inpaintingLayoutStatesEqual(
  left: readonly InpaintingBlockLayoutState[] | undefined,
  right: readonly InpaintingBlockLayoutState[] | undefined,
): boolean {
  return isDeepStrictEqual(left ?? [], right ?? []);
}

export function pageMatchesInpaintingLayoutStates(
  page: Pick<MangaPage, "blocks">,
  expected: readonly InpaintingBlockLayoutState[] | undefined,
): boolean {
  if (!expected || expected.length === 0) {
    return true;
  }
  for (const state of expected) {
    if (hasOwnTranslatedText(state)) {
      assertStoredTranslatedText(state.translatedText);
    }
  }
  return inpaintingLayoutStatesEqual(
    captureSelectedInpaintingLayoutStates(
      page,
      expected.map((state) => state.blockId),
      (index) => hasOwnTranslatedText(expected[index]),
    ),
    expected,
  );
}

export function cloneInpaintingLayoutStates(
  states: readonly InpaintingBlockLayoutState[] | undefined,
): InpaintingBlockLayoutState[] | undefined {
  return states ? cloneSerializable([...states]) : undefined;
}

function assertStoredRenderBbox(bbox: BBox | null): void {
  if (
    bbox &&
    (!Number.isFinite(bbox.x) ||
      !Number.isFinite(bbox.y) ||
      !Number.isFinite(bbox.w) ||
      !Number.isFinite(bbox.h) ||
      bbox.w <= 0 ||
      bbox.h <= 0)
  ) {
    throw new Error("말풍선 배치 기록의 렌더링 영역이 올바르지 않습니다.");
  }
}

function assertStoredTranslatedText(value: unknown): asserts value is string {
  if (typeof value !== "string") {
    throw new Error("말풍선 배치 기록의 번역문이 올바르지 않습니다.");
  }
}

function hasOwnTranslatedText(
  state: InpaintingBlockLayoutState | undefined,
): boolean {
  return (
    state !== undefined &&
    Object.prototype.hasOwnProperty.call(state, "translatedText")
  );
}

function cloneSerializable<T>(value: T): T {
  return structuredClone(value);
}
