import { createMangaDomainGateway } from "./mangaGateway";

export const libraryGateway = createMangaDomainGateway("Library", [
  "createImport",
  "cancelWebImportScan",
  "deleteChapter",
  "deletePage",
  "deleteWork",
  "discardImportPreview",
  "discardWebImportSession",
  "exportReviewText",
  "exportWorkShare",
  "getChapterStoryMemory",
  "getPathForFile",
  "getLibrary",
  "getPageImageDataUrl",
  "getWorkContextUsage",
  "getWorkResearchTitle",
  "getWorkStyleGuide",
  "importReviewText",
  "importWorkShare",
  "openChapter",
  "onWebImportProgress",
  "prepareWebImport",
  "previewFolderImport",
  "previewDroppedImport",
  "previewImagesImport",
  "previewPdfImport",
  "previewWorkShareImport",
  "previewZipFolderImport",
  "previewZipImport",
  "renameChapter",
  "renameWork",
  "reorderChapters",
  "reorderPages",
  "resetWorkContext",
  "saveChapterStoryMemory",
  "savePageBlocks",
  "savePagesBlocks",
  "saveTextFile",
  "saveWorkResearchTitle",
  "saveWorkStyleGuide",
  "scanWebImport",
] as const);
