import { createMangaDomainGateway } from "./mangaGateway";

export const libraryGateway = createMangaDomainGateway("Library", [
  "createImport",
  "deleteChapter",
  "deletePage",
  "deleteWork",
  "exportReviewText",
  "exportWorkShare",
  "getChapterStoryMemory",
  "getLibrary",
  "getPageImageDataUrl",
  "getWorkContextUsage",
  "getWorkStyleGuide",
  "importReviewText",
  "importWorkShare",
  "openChapter",
  "previewFolderImport",
  "previewImagesImport",
  "previewWorkShareImport",
  "previewZipFolderImport",
  "previewZipImport",
  "renameChapter",
  "renameWork",
  "reorderChapters",
  "reorderPages",
  "resetWorkContext",
  "saveChapterStoryMemory",
  "savePageBlocks",
  "savePagesBlocks",
  "saveTextFile",
  "saveWorkStyleGuide",
] as const);
