import { createMangaDomainGateway } from "./mangaGateway";

export const settingsGateway = createMangaDomainGateway("Settings", [
  "discoverApiModels",
  "getAppUpdateInfo",
  "getCodexAccount",
  "getRuntimeCapabilities",
  "getSettings",
  "getDefaultSettings",
  "getUiLocale",
  "loginCodexAccount",
  "logoutCodexAccount",
  "onModelTestEvent",
  "onUiLocaleChanged",
  "openAmdHipSdkDownload",
  "openApiProviderPage",
  "openVertexSetupPage",
  "openReleasesPage",
  "pickLocalMmprojFile",
  "pickLocalModelFile",
  "pickVertexServiceAccountFile",
  "resetSettings",
  "saveSettings",
  "testModelSettings",
] as const);
