export const DEFAULT_GEMMA_CONTEXT_TOKENS = 32_768;

const DEFAULT_GEMMA_INPUT_RESERVE_TOKENS = 8_192;

export const DEFAULT_GEMMA_MAX_TOKENS =
  DEFAULT_GEMMA_CONTEXT_TOKENS - DEFAULT_GEMMA_INPUT_RESERVE_TOKENS;
