import type { useBlockEditingActions } from "../../hooks/useBlockEditingActions";
import type { useConfirmDialog } from "../../hooks/useConfirmDialog";
import type { useChapterPersistence } from "../../hooks/useChapterPersistence";
import type { UpdateCurrentChapter } from "../../hooks/useCurrentChapterUpdater";
import type { useImportShareActions } from "../../hooks/useImportShareActions";
import type { useImportShareModalController } from "../../hooks/useImportShareModalController";
import type { useInpaintingActions } from "../../hooks/useInpaintingActions";
import type { useInpaintingContextBridge } from "../../hooks/useInpaintingContextBridge";
import type { useLibraryActions } from "../../hooks/useLibraryActions";
import type { useLinkedWorkspaceController } from "../../hooks/useLinkedWorkspaceController";
import type { LibraryDropImportController } from "../../hooks/useLibraryDropImport";
import type { usePageNavigationHandlers } from "../../hooks/usePageNavigationHandlers";
import type { usePageRetranslationAction } from "../../hooks/usePageRetranslationAction";
import type { useSettingsDialog } from "../../hooks/useSettingsDialog";
import type { useStatusLog } from "../../hooks/useStatusLog";
import type { useTranslationActions } from "../../hooks/useTranslationActions";
import type { useWorkspacePointerHandlers } from "../../hooks/useWorkspacePointerHandlers";
import type { WorkspaceHistoryController } from "../../hooks/useWorkspaceHistory";
import type { usePanelBridgeHost } from "../../panels/usePanelBridgeHost";
import type { AppSessionViewProps } from "./AppSessionView";
import type { useAppSessionBridgeActions } from "./useAppSessionBridgeActions";
import type { AppSessionCoreState } from "./useAppSessionCoreState";
import type { useAppSessionDerivedState } from "./useAppSessionDerivedState";
import type { useAppSessionUiState } from "./useAppSessionUiState";
import type { useInpaintingGuidePreference } from "./useInpaintingGuidePreference";
import type { useCompletionSoundController } from "../../hooks/useCompletionSound";

type OperationActivityController = {
  activity: AppSessionViewProps["rightRailProps"]["operationActivity"];
  active: boolean;
  libraryMutationBlocked: boolean;
  cancel: () => Promise<void>;
  clearTerminal: () => void;
};

export type AppSessionViewModel = {
  blockEditingActions: ReturnType<typeof useBlockEditingActions>;
  bridgeActions: ReturnType<typeof useAppSessionBridgeActions>;
  completionSound: ReturnType<typeof useCompletionSoundController>;
  commands: AppSessionViewProps["commandPaletteProps"]["commands"];
  confirmController: ReturnType<typeof useConfirmDialog>;
  core: AppSessionCoreState;
  derivedState: ReturnType<typeof useAppSessionDerivedState>;
  guidePreference: ReturnType<typeof useInpaintingGuidePreference>;
  importShareActions: ReturnType<typeof useImportShareActions>;
  importShareModal: ReturnType<typeof useImportShareModalController>;
  inpaintingActions: ReturnType<typeof useInpaintingActions>;
  inpaintingBridge: ReturnType<typeof useInpaintingContextBridge>;
  libraryActions: ReturnType<typeof useLibraryActions>;
  linkedWorkspace: ReturnType<typeof useLinkedWorkspaceController>;
  operationActivity: OperationActivityController;
  libraryDrop: LibraryDropImportController;
  panelBridge: ReturnType<typeof usePanelBridgeHost>;
  persistence: ReturnType<typeof useChapterPersistence>;
  pageNavigationHandlers: ReturnType<typeof usePageNavigationHandlers>;
  pointerHandlers: ReturnType<typeof useWorkspacePointerHandlers>;
  retranslatePage: ReturnType<typeof usePageRetranslationAction>;
  settingsDialog: ReturnType<typeof useSettingsDialog>;
  statusLog: ReturnType<typeof useStatusLog>;
  translationActions: ReturnType<typeof useTranslationActions>;
  uiState: ReturnType<typeof useAppSessionUiState>;
  updateCurrentChapter: UpdateCurrentChapter;
  workspaceHistory: WorkspaceHistoryController;
};
