// @ts-check
const KiB = 1024;
const MiB = KiB * 1024;
const GiB = MiB * 1024;

const MAX_REMOTE_MODEL_FILE_BYTES = 96 * GiB;
const MAX_REMOTE_DRAFT_MODEL_FILE_BYTES = 48 * GiB;
const MAX_REMOTE_MMPROJ_FILE_BYTES = 16 * GiB;
const MAX_REMOTE_RUNTIME_ARCHIVE_BYTES = 16 * GiB;
const MAX_REMOTE_SUPPORT_ASSET_BYTES = 8 * GiB;
const MAX_MODEL_DOWNLOAD_AGGREGATE_BYTES = 160 * GiB;
const DEFAULT_DOWNLOAD_ABSOLUTE_TIMEOUT_MS = 24 * 60 * 60 * 1000;
const MIN_DOWNLOAD_ABSOLUTE_TIMEOUT_MS = 10 * 60 * 1000;
const MAX_DOWNLOAD_ABSOLUTE_TIMEOUT_MS = 72 * 60 * 60 * 1000;

module.exports = {
  MAX_REMOTE_MODEL_FILE_BYTES,
  MAX_REMOTE_DRAFT_MODEL_FILE_BYTES,
  MAX_REMOTE_MMPROJ_FILE_BYTES,
  MAX_REMOTE_RUNTIME_ARCHIVE_BYTES,
  MAX_REMOTE_SUPPORT_ASSET_BYTES,
  MAX_MODEL_DOWNLOAD_AGGREGATE_BYTES,
  DEFAULT_DOWNLOAD_ABSOLUTE_TIMEOUT_MS,
  MIN_DOWNLOAD_ABSOLUTE_TIMEOUT_MS,
  MAX_DOWNLOAD_ABSOLUTE_TIMEOUT_MS,
};
